[main]
version       = "1.0.0"
tag           = true
extraCommands = ["git push", "git push --tags"]
serialize     = "{version}-{banner}"
[[operate]]
location = "cmd/hackbox/hackbox.go"
search   = "__version__ = \"{}\""
replace  = "__version__ = \"{}\""
